# Use an official Python runtime as a parent image
FROM python:3.6

# Set the working directory to /app
WORKDIR /detect_objects

# Copy the current directory contents into the container at /app
COPY . /detect_objects

# Install any needed packages specified in requirements.txt
RUN pip3 install --trusted-host pypi.python.org -r requirements.txt

# Make port 80? available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME World
ENV PYTHONPATH detect_objects

# Run app.py when the container launches
CMD ["python3", "detect_objects/"]